const actionTypes = {
  SEARCH: {
    SET_KEYWORD: "SET_KEYWORD",
    SET_SEARCH_STATUS: "SET_SEARCH_STATUS",
    SET_RESULTS: "SET_RESULTS",
    SET_ON_PAGING: "SET_ON_PAGING",
    SET_SUGGESTIONS: "SET_SUGGESTIONS",
  },
};

export { actionTypes };
